
package condor;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * gSOAP 2.7.10 generated service definition
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "condorCollector", targetNamespace = "urn:condor", wsdlLocation = "file:/C:/Users/lipei/git/htcweb/web/wsdl/condorCollector.wsdl")
public class CondorCollector
    extends Service
{

    private final static URL CONDORCOLLECTOR_WSDL_LOCATION;
    private final static WebServiceException CONDORCOLLECTOR_EXCEPTION;
    private final static QName CONDORCOLLECTOR_QNAME = new QName("urn:condor", "condorCollector");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/lipei/git/htcweb/web/wsdl/condorCollector.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONDORCOLLECTOR_WSDL_LOCATION = url;
        CONDORCOLLECTOR_EXCEPTION = e;
    }

    public CondorCollector() {
        super(__getWsdlLocation(), CONDORCOLLECTOR_QNAME);
    }

    public CondorCollector(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONDORCOLLECTOR_QNAME, features);
    }

    public CondorCollector(URL wsdlLocation) {
        super(wsdlLocation, CONDORCOLLECTOR_QNAME);
    }

    public CondorCollector(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONDORCOLLECTOR_QNAME, features);
    }

    public CondorCollector(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CondorCollector(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CondorCollectorPortType
     */
    @WebEndpoint(name = "condorCollector")
    public CondorCollectorPortType getCondorCollector() {
        return super.getPort(new QName("urn:condor", "condorCollector"), CondorCollectorPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CondorCollectorPortType
     */
    @WebEndpoint(name = "condorCollector")
    public CondorCollectorPortType getCondorCollector(WebServiceFeature... features) {
        return super.getPort(new QName("urn:condor", "condorCollector"), CondorCollectorPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONDORCOLLECTOR_EXCEPTION!= null) {
            throw CONDORCOLLECTOR_EXCEPTION;
        }
        return CONDORCOLLECTOR_WSDL_LOCATION;
    }

}
