
package condor;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * gSOAP 2.7.10 generated service definition
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "condorSchedd", targetNamespace = "urn:condor", wsdlLocation = "file:/C:/Users/lipei/git/htcweb/web/wsdl/condorSchedd.wsdl")
public class CondorSchedd
    extends Service
{

    private final static URL CONDORSCHEDD_WSDL_LOCATION;
    private final static WebServiceException CONDORSCHEDD_EXCEPTION;
    private final static QName CONDORSCHEDD_QNAME = new QName("urn:condor", "condorSchedd");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/lipei/git/htcweb/web/wsdl/condorSchedd.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONDORSCHEDD_WSDL_LOCATION = url;
        CONDORSCHEDD_EXCEPTION = e;
    }

    public CondorSchedd() {
        super(__getWsdlLocation(), CONDORSCHEDD_QNAME);
    }

    public CondorSchedd(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONDORSCHEDD_QNAME, features);
    }

    public CondorSchedd(URL wsdlLocation) {
        super(wsdlLocation, CONDORSCHEDD_QNAME);
    }

    public CondorSchedd(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONDORSCHEDD_QNAME, features);
    }

    public CondorSchedd(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CondorSchedd(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CondorScheddPortType
     */
    @WebEndpoint(name = "condorSchedd")
    public CondorScheddPortType getCondorSchedd() {
        return super.getPort(new QName("urn:condor", "condorSchedd"), CondorScheddPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CondorScheddPortType
     */
    @WebEndpoint(name = "condorSchedd")
    public CondorScheddPortType getCondorSchedd(WebServiceFeature... features) {
        return super.getPort(new QName("urn:condor", "condorSchedd"), CondorScheddPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONDORSCHEDD_EXCEPTION!= null) {
            throw CONDORSCHEDD_EXCEPTION;
        }
        return CONDORSCHEDD_WSDL_LOCATION;
    }

}
