
package condor;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "condorCollectorPortType", targetNamespace = "urn:condor")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CondorCollectorPortType {


    /**
     * Service definition of function condor__getVersionString
     * 
     * @return
     *     returns condor.StringAndStatus
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "getVersionString", targetNamespace = "urn:condor", className = "condor.GetVersionString")
    @ResponseWrapper(localName = "getVersionStringResponse", targetNamespace = "urn:condor", className = "condor.GetVersionStringResponse")
    public StringAndStatus getVersionString();

    /**
     * Service definition of function condor__getPlatformString
     * 
     * @return
     *     returns condor.StringAndStatus
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "getPlatformString", targetNamespace = "urn:condor", className = "condor.GetPlatformString")
    @ResponseWrapper(localName = "getPlatformStringResponse", targetNamespace = "urn:condor", className = "condor.GetPlatformStringResponse")
    public StringAndStatus getPlatformString();

    /**
     * Service definition of function condor__insertAd
     * 
     * @param ad
     * @param type
     * @return
     *     returns condor.Status
     */
    @WebMethod
    @WebResult(name = "status", targetNamespace = "")
    @RequestWrapper(localName = "insertAd", targetNamespace = "urn:condor", className = "condor.InsertAd")
    @ResponseWrapper(localName = "insertAdResponse", targetNamespace = "urn:condor", className = "condor.InsertAdResponse")
    public Status insertAd(
        @WebParam(name = "type", targetNamespace = "")
        ClassAdType type,
        @WebParam(name = "ad", targetNamespace = "")
        ClassAdStruct ad);

    /**
     * Service definition of function condor__queryStartdAds
     * 
     * @param constraint
     * @return
     *     returns condor.ClassAdStructArray
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "queryStartdAds", targetNamespace = "urn:condor", className = "condor.QueryStartdAds")
    @ResponseWrapper(localName = "queryStartdAdsResponse", targetNamespace = "urn:condor", className = "condor.QueryStartdAdsResponse")
    public ClassAdStructArray queryStartdAds(
        @WebParam(name = "constraint", targetNamespace = "")
        String constraint);

    /**
     * Service definition of function condor__queryScheddAds
     * 
     * @param constraint
     * @return
     *     returns condor.ClassAdStructArray
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "queryScheddAds", targetNamespace = "urn:condor", className = "condor.QueryScheddAds")
    @ResponseWrapper(localName = "queryScheddAdsResponse", targetNamespace = "urn:condor", className = "condor.QueryScheddAdsResponse")
    public ClassAdStructArray queryScheddAds(
        @WebParam(name = "constraint", targetNamespace = "")
        String constraint);

    /**
     * Service definition of function condor__queryMasterAds
     * 
     * @param constraint
     * @return
     *     returns condor.ClassAdStructArray
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "queryMasterAds", targetNamespace = "urn:condor", className = "condor.QueryMasterAds")
    @ResponseWrapper(localName = "queryMasterAdsResponse", targetNamespace = "urn:condor", className = "condor.QueryMasterAdsResponse")
    public ClassAdStructArray queryMasterAds(
        @WebParam(name = "constraint", targetNamespace = "")
        String constraint);

    /**
     * Service definition of function condor__querySubmittorAds
     * 
     * @param constraint
     * @return
     *     returns condor.ClassAdStructArray
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "querySubmittorAds", targetNamespace = "urn:condor", className = "condor.QuerySubmittorAds")
    @ResponseWrapper(localName = "querySubmittorAdsResponse", targetNamespace = "urn:condor", className = "condor.QuerySubmittorAdsResponse")
    public ClassAdStructArray querySubmittorAds(
        @WebParam(name = "constraint", targetNamespace = "")
        String constraint);

    /**
     * Service definition of function condor__queryLicenseAds
     * 
     * @param constraint
     * @return
     *     returns condor.ClassAdStructArray
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "queryLicenseAds", targetNamespace = "urn:condor", className = "condor.QueryLicenseAds")
    @ResponseWrapper(localName = "queryLicenseAdsResponse", targetNamespace = "urn:condor", className = "condor.QueryLicenseAdsResponse")
    public ClassAdStructArray queryLicenseAds(
        @WebParam(name = "constraint", targetNamespace = "")
        String constraint);

    /**
     * Service definition of function condor__queryStorageAds
     * 
     * @param constraint
     * @return
     *     returns condor.ClassAdStructArray
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "queryStorageAds", targetNamespace = "urn:condor", className = "condor.QueryStorageAds")
    @ResponseWrapper(localName = "queryStorageAdsResponse", targetNamespace = "urn:condor", className = "condor.QueryStorageAdsResponse")
    public ClassAdStructArray queryStorageAds(
        @WebParam(name = "constraint", targetNamespace = "")
        String constraint);

    /**
     * Service definition of function condor__queryAnyAds
     * 
     * @param constraint
     * @return
     *     returns condor.ClassAdStructArray
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "queryAnyAds", targetNamespace = "urn:condor", className = "condor.QueryAnyAds")
    @ResponseWrapper(localName = "queryAnyAdsResponse", targetNamespace = "urn:condor", className = "condor.QueryAnyAdsResponse")
    public ClassAdStructArray queryAnyAds(
        @WebParam(name = "constraint", targetNamespace = "")
        String constraint);

}
